#!/bin/sh
#
# Typically, this script is run by calling
#
#    pub global run rpi_gpio:build_native
#
# See README for setup instructions

# exit on error
set -e

cd $(dirname $0)
echo building rpi_gpio in `pwd`

####################################################################
# Build rpi_gpio native library

g++ -fPIC -c rpi_gpio_ext.cc
# use --no-undefined to check for missing libraries
gcc -shared -lpthread -Wl,-soname,librpi_gpio_ext.so -o librpi_gpio_ext.so rpi_gpio_ext.o

# Copy the library
cp librpi_gpio_ext.so ../librpi_gpio_ext.so

# echo "exported symbols"
# nm -g ../librpi_gpio_ext.so | grep ' T '

echo "gcc build complete"
