#!/bin/sh
#
# Build the librpi_gpio_ext.so native library on the Raspberry Pi.
# The generated native library file is referenced by rpi_gpio.dart via
# import 'dart-ext:rpi_gpio_ext'
#
# Arguments: <buildScriptVersion> <DartSdkPath>
#
# Typically, this script is run by calling
#
#    pub global run rpi_gpio:build_native
#
# See README for setup instructions

# exit on error
set -e

#DARTVM=$(readlink `which dart`)
#DARTBIN=$(dirname $DARTVM)
#DARTSDK=$(dirname $DARTBIN)
DARTSDK=$2

cd $(dirname $0)
echo building rpi_gpio in `pwd`

####################################################################
# Build rpi_gpio native library

g++ -fPIC -I$DARTSDK/ -c rpi_gpio_ext.cc
# use --no-undefined to check for missing libraries
gcc -shared -lpthread -Wl,-soname,librpi_gpio_ext.so -o librpi_gpio_ext.so rpi_gpio_ext.o

# Copy the library
cp librpi_gpio_ext.so ../librpi_gpio_ext.so
