#!/bin/sh
#
# Build the librpi_gpio_ext.so external library on the Raspberry Pi.
# This file is referenced by rpi_gpio.dart via
# import 'dart-ext:rpi_gpio_ext'
#

# exit on error
set -e

DARTVM=$(readlink `which dart`)
DARTBIN=$(dirname $DARTVM)
DARTSDK=$(dirname $DARTBIN)

# The package's tool/src directory
cd $(dirname $0)/src
echo building in `pwd`

# Build the wiring pi library
#cd wiringPi
#sudo make install
#cd ..

g++ -fPIC -I$DARTSDK/ -c rpi_gpio_ext.cc
gcc -shared -Wl,wiringPi/wiringPi.o,wiringPi/softPwm.o,wiringPi/softTone.o,-soname,librpi_gpio_ext.so -o librpi_gpio_ext.so rpi_gpio_ext.o

# Copy the library
cp librpi_gpio_ext.so ../../lib/librpi_gpio_ext.so
